services:
  postgres:
    container_name: postgres  
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    ports:
      - "5345:5341"
      - "5346:80"
    environment:
      ACCEPT_EULA: Y
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
  
volumes:
  postgres-data:
  minio_data: